version: '3.8'

services:
  # SERVIÇO DA API
  api:
    build: .
    container_name: sensorflow-api
    restart: always
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 45s
