{
 "title": "Dashboard database IoT",
 "tags": [
  "database",
  "iot"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ultima Temperatura",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  temperature\r\nFROM data\r\nORDER BY time_recorded DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Ultima Umidade",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  humidity\r\nFROM data\r\nORDER BY time_recorded DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Media de Temperatura por Sensor",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sensor_id,\r\n  AVG(temperature) as \"Média de Temperatura\"\r\nFROM data\r\nWHERE\r\n  CAST(date_recorded AS TIMESTAMP) + time_recorded BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY sensor_id\r\nORDER BY \"Média de Temperatura\" DESC;"
    }
   ]
  },
  {
   "title": "Quantidade de database",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(DISTINCT sensor_id) AS \"database Ativos\"\r\nFROM data\r\nWHERE\r\n  CAST(date_recorded AS TIMESTAMP) + time_recorded BETWEEN $__timeFrom() AND $__timeTo();"
    }
   ]
  },
  {
   "title": "Evolução das Métricas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  -- Combina data e hora em um único campo de timestamp chamado \"time\"\r\n  CAST(date_recorded AS TIMESTAMP) + time_recorded AS \"time\",\r\n  temperature AS \"Temperatura\",\r\n  humidity AS \"Umidade\",\r\n  pressure AS \"Pressão\",\r\n  sensor_id\r\nFROM data\r\nWHERE\r\n  -- Filtra os dados pelo intervalo de tempo selecionado no Grafana\r\n  CAST(date_recorded AS TIMESTAMP) + time_recorded BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY \"time\" ASC;"
    }
   ]
  },
  {
   "title": "Ultimas Leituras",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CAST(date_recorded AS TIMESTAMP) + time_recorded AS \"time\",\r\n  sensor_id,\r\n  temperature,\r\n  humidity,\r\n  pressure\r\nFROM data\r\nORDER BY \"time\" DESC\r\nLIMIT 10;"
    }
   ]
  }
 ]
}